
  name: level
  version: '0.1'
  summary: Print the level of the James River at Westham Bridge
  description: long description
  grade: stable
  confinement: strict

  parts:
    riverlevel:
      plugin: python
      requirements: requirements.txt
      python-version: python3
      source: .
      
  apps:
   level:
     command: python3 level.py
